name: release

on:
  release:
    types: [ created, edited ]

jobs:
  selefra_release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Unshallow
        run: git fetch
      - name: Use Golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.19
      - name: git
        run: git config --global url.https://${{ secrets.SELEFRA_TOKEN }}@github.com/.insteadOf https://github.com/

      #      - name: Get the release version
      #        id: get_version
      #        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      #      - name: Set Version
      #        run: |
      #          sed -i "s#{{version}}#${{ steps.get_version.outputs.VERSION }}#g" cmd/version/version.go
      #          cat cmd/version/version.go

      - name: Run GoReleaser
        if: "github.event.release.prerelease"
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --skip-publish --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        if: "github.event.release.prerelease"
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*checksums.txt
            dist/*.tar.gz
            dist/*.zip
          prerelease: true
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        if: "!github.event.release.prerelease"
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.SELEFRA_TOKEN }}

  # release Windows package
  windows-release:
    runs-on: windows-latest
    steps:
      - name: Choco help
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: -h

      - name: Setup GoReleaser
        run: |
          rm -rf .goreleaser.yml
          mv .goreleaser-windows.yml .goreleaser.yml
      - name: Run GoReleaser
        if: "github.event.release.prerelease"
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --skip-publish --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        if: "!github.event.release.prerelease"
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.SELEFRA_TOKEN }}
          CHOCOLATEY_API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }}